spring:
  datasource:
    url: jdbc:h2:file:/usr/local/src/bitterling/bitterling_db
    driver-class-name: org.h2.Driver
    username: sa
    password: jinelei
  h2:
    console:
      enabled: false
logging:
  level:
    root: warn
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql: warn
    com.jinelei.bitterling: info
springdoc:
  api-docs:
    enabled: false
